version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      npm-production:
        patterns:
          - "*"
        dependency-type: production
        update-types:
          - minor
          - patch
      npm-development:
        patterns:
          - "*"
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "06:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
