import type { ValidationError } from "../types.js";
import type { LoadedRecord } from "./records.js";
import { asApproval, type Approval } from "./review-records.js";

const invariant = "approval-mode";

export type ApprovalMode = "synthetic" | "self-asserted" | "human-verified";

const approvalModes = new Set<string>([
  "synthetic",
  "self-asserted",
  "human-verified",
]);

export function isApprovalMode(value: string): value is ApprovalMode {
  return approvalModes.has(value);
}

/**
 * Resolves the assurance an approval actually carries from its recorded
 * evidence. It never reads the declared mode: a claim is the thing being
 * checked, not the check. "human-verified" becomes reachable only when
 * signature verification is added, so no record can assert it today.
 */
export function resolveApprovalMode(approval: Approval): ApprovalMode {
  return approval.syntheticTestEvidence ? "synthetic" : "self-asserted";
}

export function approvalModeLabel(mode: ApprovalMode): string {
  switch (mode) {
    case "synthetic":
      return "Synthetic test evidence. Generated by the offline harness; no human decision was made.";
    case "human-verified":
      return "Human-verified. The approver signature verifies against the case approval key.";
    default:
      return "Self-asserted. Recorded without verification of the approver's identity.";
  }
}

export function validateApprovalModes(
  records: LoadedRecord[],
): ValidationError[] {
  const errors: ValidationError[] = [];

  for (const approval of records
    .map(asApproval)
    .filter((value): value is Approval => value !== undefined)) {
    const claimed = approval.claimedMode;
    if (claimed === undefined) {
      continue;
    }
    if (!isApprovalMode(claimed)) {
      errors.push({
        file: approval.file,
        invariant,
        message: `Approval declares unknown assurance mode "${claimed}".`,
        remediation: `Set extensions.approvalMode to one of ${[...approvalModes].sort().join(", ")}.`,
      });
      continue;
    }

    const resolved = resolveApprovalMode(approval);
    if (claimed !== resolved) {
      errors.push({
        file: approval.file,
        invariant,
        message: `Approval declares assurance mode "${claimed}" but its recorded evidence supports only "${resolved}".`,
        remediation:
          "Declare the mode the evidence supports. A stronger claim is never accepted on the strength of the claim itself.",
      });
    }
  }

  return errors;
}
